name: Snyk Full Repo Security Scan (.NET)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore all projects
        run: |
          for file in $(find . -name '*.csproj'); do
            echo "Restoring $file"
            dotnet restore "$file"
          done

      - name: Build all projects
        run: |
          for file in $(find . -name '*.csproj'); do
            echo "Building $file"
            dotnet build "$file" --no-restore --configuration Release
          done

      - name: Install Snyk CLI & snyk-to-html
        run: |
          npm install -g snyk snyk-to-html

      - name: Run Snyk and generate reports
        run: |
          snyk test --all-projects --json > snyk-report.json || true
          snyk test --all-projects --json | snyk-to-html -o snyk-report.html || true
        env:
          SNYK_TOKEN: 8737b053-aafe-4c3b-9435-33136831924a

      - name: Upload reports to Azure Blob Storage
        run: |
          timestamp=$(date +'%Y%m%d-%H%M%S')
          container_url="https://snyk.blob.core.windows.net/report"

          azcopy copy "snyk-report.json" "${container_url}/snyk-report-${timestamp}.json?sp=racwi&st=2025-06-03T12:55:47Z&se=2025-08-29T20:55:47Z&sv=2024-11-04&sr=c&sig=pBhuO60j7e0d7v9exxTNTZuuG3IMyzS%2BTw0%2F7geJQNY%3D" --overwrite=true
          azcopy copy "snyk-report.html" "${container_url}/snyk-report-${timestamp}.html?sp=racwi&st=2025-06-03T12:55:47Z&se=2025-08-29T20:55:47Z&sv=2024-11-04&sr=c&sig=pBhuO60j7e0d7v9exxTNTZuuG3IMyzS%2BTw0%2F7geJQNY%3D" --overwrite=true

      - name: Upload log message
        run: |
          echo "Snyk reports uploaded to Azure Blob Storage with timestamp: $timestamp"
