name: Snyk Full Repo Security Scan (.NET)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore all projects
        run: |
          for file in $(find . -name '*.csproj'); do
            echo "Restoring $file"
            dotnet restore "$file"
          done

      - name: Build all projects
        run: |
          for file in $(find . -name '*.csproj'); do
            echo "Building $file"
            dotnet build "$file" --no-restore --configuration Release
          done

      - name: Run Snyk on all .csproj files
        uses: snyk/actions/dotnet@master
        with:
          args: --all-projects
        env:
          SNYK_TOKEN: 8737b053-aafe-4c3b-9435-33136831924a
